/* 사이드바 서재 뷰에서 앨범 리스트 띄우기*/
export const ALBUM_LIST_LOADING_REQUEST = 'ALBUM_LIST_LOADING_REQUEST';
export const ALBUM_LIST_LOADING_SUCCESS = 'ALBUM_LIST_LOADING_SUCCESS';
export const ALBUM_LIST_LOADING_FAILURE = 'ALBUM_LIST_LOADING_FAILURE';

/* 앨범 리스트에서 앨범 클릭시 보이는 정보 */
export const ALBUM_LOADING_REQUEST = 'ALBUM_LOADING_REQUEST';
export const ALBUM_LOADING_SUCCESS = 'ALBUM_LOADING_SUCCESS';
export const ALBUM_LOADING_FAILURE = 'ALBUM_LOADING_FAILURE';
