export const ALBUM_LIST_LOADING_REQUEST = 'ALBUM_LIST_LOADING_REQUEST';
export const ALBUM_LIST_LOADING_SUCCESS = 'ALBUM_LIST_LOADING_SUCCESS';
export const ALBUM_LIST_LOADING_FAILURE = 'ALBUM_LIST_LOADING_FAILURE';
export const ALBUM_LOADING_REQUEST = 'ALBUM_LOADING_REQUEST';
export const ALBUM_LOADING_SUCCESS = 'ALBUM_LOADING_SUCCESS';
export const ALBUM_LOADING_FAILURE = 'ALBUM_LOADING_FAILURE';
