/* 유저 로그인 정보 */
export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST';
export const USER_LOADING_SUCCESS = 'USER_LOADING_SUCCESS';
export const USER_LOADING_FAILURE = 'USER_LOADING_FAILURE';

/* 유저 로그아웃 정보 */
export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

/* 유저 등록 이미지 */
export const USIM_LOADING_REQUEST = 'USIM_LOADING_REQUEST';
export const USIM_LOADING_SUCCESS = 'USIM_LOADING_SUCCESS';
export const USIM_LOADING_FAILURE = 'USIM_LOADING_FAILURE';
export const USIM_CREATE_REQUEST = 'USIM_CREATE_REQUEST';
export const USIM_CREATE_SUCCESS = 'USIM_CREATE_SUCCESS';
export const USIM_CREATE_FAILURE = 'USIM_CREATE_FAILURE';

/* 사이드바 서재 뷰에서 앨범 리스트 띄우기 */
export const ALBUM_LIST_LOADING_REQUEST = 'ALBUM_LIST_LOADING_REQUEST';
export const ALBUM_LIST_LOADING_SUCCESS = 'ALBUM_LIST_LOADING_SUCCESS';
export const ALBUM_LIST_LOADING_FAILURE = 'ALBUM_LIST_LOADING_FAILURE';

/* 앨범 리스트에서 앨범 클릭시 보이는 정보 */
export const ALBUM_LOADING_REQUEST = 'ALBUM_LOADING_REQUEST';
export const ALBUM_LOADING_SUCCESS = 'ALBUM_LOADING_SUCCESS';
export const ALBUM_LOADING_FAILURE = 'ALBUM_LOADING_FAILURE';

/* 친구 사이드바 서재 뷰에서 앨범 리스트 띄우기 */
export const FRIEND_ALBUM_LIST_LOADING_REQUEST = 'FRIEND_ALBUM_LIST_LOADING_REQUEST';
export const FRIEND_ALBUM_LIST_LOADING_SUCCESS = 'FRIEND_ALBUM_LIST_LOADING_SUCCESS';
export const FRIEND_ALBUM_LIST_LOADING_FAILURE = 'FRIEND_ALBUM_LIST_LOADING_FAILURE';

/* 친구 앨범 리스트에서 앨범 클릭시 보이는 정보 */
export const FRIEND_ALBUM_LOADING_REQUEST = 'FRIEND_ALBUM_LOADING_REQUEST';
export const FRIEND_ALBUM_LOADING_SUCCESS = 'FRIEND_ALBUM_LOADING_SUCCESS';
export const FRIEND_ALBUM_LOADING_FAILURE = 'FRIEND_ALBUM_LOADING_FAILURE';

/* 앨범 생성 */
export const ALBUM_CREATE_REQUEST = 'ALBUM_CREATE_REQUEST';
export const ALBUM_CREATE_SUCCESS = 'ALBUM_CREATE_SUCCESS';
export const ALBUM_CREATE_FAILURE = 'ALBUM_CREATE_FAILURE';

/* 앨범 수정 */
export const ALBUM_UPDATE_REQUEST = 'ALBUM_UPDATE_REQUEST';
export const ALBUM_UPDATE_SUCCESS = 'ALBUM_UPDATE_SUCCESS';
export const ALBUM_UPDATE_FAILURE = 'ALBUM_UPDATE_FAILURE';

/* 앨범 삭제 */
export const ALBUM_DELETE_REQUEST = 'ALBUM_DELETE_REQUEST';
export const ALBUM_DELETE_SUCCESS = 'ALBUM_DELETE_SUCCESS';
export const ALBUM_DELETE_FAILURE = 'ALBUM_DELETE_FAILURE';

/* 사이드바 비디오 뷰에서 카드 리스트 띄우기 */
export const CARD_LIST_LOADING_REQUEST = 'CARD_LIST_LOADING_REQUEST';
export const CARD_LIST_LOADING_SUCCESS = 'CARD_LIST_LOADING_SUCCESS';
export const CARD_LIST_LOADING_FAILURE = 'CARD_LIST_LOADING_FAILURE';

export const CARD_LIST_FILTER_EXPRESSION = 'CARD_LIST_FILTER_EXPRESSION';
export const CARD_LIST_FILTER_EXPRESSION_SUCCESS = 'CARD_LIST_FILTER_EXPRESSION_SUCCESS';
export const CARD_LIST_FILTER_DATE = 'CARD_LIST_FILTER_DATE';
export const CARD_LIST_FILTER_DATE_SUCCESS = 'CARD_LIST_FILTER_DATE_SUCCESS';

/* 비디오 뷰에서 카드 클릭시 보이는 정보 */
export const CARD_LOADING_REQUEST = 'CARD_LOADING_REQUEST';
export const CARD_LOADING_SUCCESS = 'CARD_LOADING_SUCCESS';
export const CARD_LOADING_FAILURE = 'CARD_LOADING_FAILURE';

/* 카드 수정 */
export const CARD_UPDATE_REQUEST = 'CARD_UPDATE_REQUEST';
export const CARD_UPDATE_SUCCESS = 'CARD_UPDATE_SUCCESS';
export const CARD_UPDATE_FAILURE = 'CARD_UPDATE_FAILURE';

/* 카드 삭제 */
export const CARD_DELETE_REQUEST = 'CARD_DELETE_REQUEST';
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS';
export const CARD_DELETE_FAILURE = 'CARD_DELETE_FAILURE';

/* 알림 추가, 삭제*/
export const ADD_NOTI = 'ADD_NOTI';
export const DELETE_NOTI = 'DELETE_NOTI';
